# Generated by Django 3.2.7 on 2021-09-08 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_img2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=0, max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('paymethod', models.CharField(default='cod', max_length=100)),
                ('totalamount', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(editable=False, max_length=50)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
