# Generated by Django 3.2.7 on 2021-09-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_no',
        ),
    ]
