# Generated by Django 3.2.7 on 2021-09-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_order_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
        ),
    ]
