# Generated by Django 3.2.7 on 2021-09-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_format'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='format',
            new_name='formatt',
        ),
    ]
