# Generated by Django 3.2.7 on 2021-09-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='client',
        ),
    ]
