# Generated by Django 3.2.7 on 2021-09-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_user_profile_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='client',
            new_name='user',
        ),
    ]
